### ISSUE TITLE
List of required Services

### ISSUE THREAD

**Issue by Muirrum** [AdHubBotDevelopers/Adhub_Services_Bot#2]
- Ban
- Kick
- Mute (with auto-unmute)
- Unban
- Help command that links back to AdHub

**Comment by mindcoding** [comment]
Added ban command
Added unban command

**Comment by Muirrum** [comment]
- Way for staff to respond to raids by verifying themselves and giving them some more permissions.

**Comment by Muirrum** [comment]
Also setup for joining new servers.
